# Generated by Django 5.2.17 on 2026-08-26 10:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "locale",
                    models.CharField(
                        choices=[("it", "Italiano"), ("en", "English"), ("zh-hans", "简体中文")],
                        default="it",
                        max_length=16,
                        verbose_name="language",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="owner",
                    ),
                ),
            ],
            options={
                "verbose_name": "conversation",
                "verbose_name_plural": "conversations",
                "ordering": ("-created_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("user", "student"), ("assistant", "assistant")],
                        max_length=16,
                        verbose_name="role",
                    ),
                ),
                ("text", models.TextField(blank=True, verbose_name="text")),
                ("locale", models.CharField(max_length=16, verbose_name="language")),
                ("complete", models.BooleanField(default=False, verbose_name="complete")),
                ("citations", models.JSONField(default=list, verbose_name="citations")),
                ("route", models.JSONField(blank=True, null=True, verbose_name="routing decision")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="qa.conversation",
                        verbose_name="conversation",
                    ),
                ),
            ],
            options={
                "verbose_name": "message",
                "verbose_name_plural": "messages",
                "ordering": ("created_at", "id"),
                "indexes": [
                    models.Index(
                        fields=["conversation", "created_at"], name="qa_message_convers_561460_idx"
                    )
                ],
            },
        ),
    ]
