# Generated by Django 5.2.17 on 2026-09-26 19:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import apps.catalog.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="AD code of the Moodle course that holds the material, such as B028451. Fixed once entered.",
                        max_length=16,
                        unique=True,
                        verbose_name="code",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="name")),
                (
                    "locale",
                    models.CharField(
                        choices=[("it", "Italiano"), ("en", "English"), ("zh-hans", "简体中文")],
                        default="it",
                        help_text="Language the name is written in.",
                        max_length=16,
                        verbose_name="language",
                    ),
                ),
            ],
            options={
                "verbose_name": "course",
                "verbose_name_plural": "courses",
                "ordering": ("code",),
            },
        ),
        migrations.CreateModel(
            name="DegreeProgramme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="The code the Cineca catalogue prints in brackets, such as B047.",
                        max_length=16,
                        unique=True,
                        verbose_name="code",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="name")),
                (
                    "locale",
                    models.CharField(
                        choices=[("it", "Italiano"), ("en", "English"), ("zh-hans", "简体中文")],
                        default="it",
                        help_text="Language the name is written in.",
                        max_length=16,
                        verbose_name="language",
                    ),
                ),
            ],
            options={
                "verbose_name": "degree programme",
                "verbose_name_plural": "degree programmes",
                "ordering": ("code",),
            },
        ),
        migrations.CreateModel(
            name="CourseEdition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "academic_year",
                    models.CharField(
                        help_text="Two consecutive years, such as 2025-2026.",
                        max_length=9,
                        validators=[apps.catalog.models.validate_academic_year],
                        verbose_name="academic year",
                    ),
                ),
                ("is_current", models.BooleanField(default=False, verbose_name="current")),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="editions",
                        to="catalog.course",
                        verbose_name="course",
                    ),
                ),
            ],
            options={
                "verbose_name": "course edition",
                "verbose_name_plural": "course editions",
                "ordering": ("course", "-academic_year"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("course", "academic_year"),
                        name="catalog_edition_unique_course_year",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("academic_year__regex", "^\\d{4}-\\d{4}$")),
                        name="catalog_edition_academic_year_format",
                        violation_error_message="An academic year is two consecutive years, such as 2025-2026.",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("is_current", True)),
                        fields=("course",),
                        name="catalog_edition_one_current_per_course",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CurriculumEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "curriculum",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The curriculum name exactly as the Cineca catalogue prints it, such as TECNICO APPLICATIVO; empty when it prints none.",
                        max_length=100,
                        verbose_name="curriculum",
                    ),
                ),
                (
                    "year_of_study",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(6),
                        ],
                        verbose_name="year of study",
                    ),
                ),
                (
                    "ad_code",
                    models.CharField(
                        help_text="The official code of the course in this curriculum. When the curriculum lists two for one course, the one listed only in this curriculum.",
                        max_length=16,
                        verbose_name="AD code",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="curriculum_entries",
                        to="catalog.course",
                        verbose_name="course",
                    ),
                ),
                (
                    "programme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="curriculum_entries",
                        to="catalog.degreeprogramme",
                        verbose_name="degree programme",
                    ),
                ),
            ],
            options={
                "verbose_name": "curriculum entry",
                "verbose_name_plural": "curriculum entries",
                "ordering": ("programme", "curriculum", "year_of_study", "ad_code"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("programme", "curriculum", "ad_code"),
                        name="catalog_entry_unique_ad_code",
                    ),
                    models.UniqueConstraint(
                        fields=("programme", "curriculum", "course"),
                        name="catalog_entry_unique_course",
                    ),
                ],
            },
        ),
    ]
