# Generated by Django 5.2.17 on 2026-09-29 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RoleAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("teacher", "teacher"), ("secretariat", "secretariat staff")],
                        max_length=16,
                        verbose_name="role",
                    ),
                ),
                (
                    "edition",
                    models.ForeignKey(
                        blank=True,
                        help_text="Teachers only.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_assignments",
                        to="catalog.courseedition",
                        verbose_name="course edition",
                    ),
                ),
                (
                    "programme",
                    models.ForeignKey(
                        blank=True,
                        help_text="Secretariat staff only.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_assignments",
                        to="catalog.degreeprogramme",
                        verbose_name="degree programme",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_assignments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "role assignment",
                "verbose_name_plural": "role assignments",
                "ordering": ("user", "role"),
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("edition__isnull", False),
                                ("programme__isnull", True),
                                ("role", "teacher"),
                            ),
                            models.Q(
                                ("edition__isnull", True),
                                ("programme__isnull", False),
                                ("role", "secretariat"),
                            ),
                            _connector="OR",
                        ),
                        name="roles_assignment_scope_fits_role",
                        violation_error_message="A teacher is assigned to an edition, secretariat staff to a programme.",
                    ),
                    models.UniqueConstraint(
                        fields=("user", "role", "programme", "edition"),
                        name="roles_assignment_unique",
                        nulls_distinct=False,
                        violation_error_message="This user already holds this role here.",
                    ),
                ],
            },
        ),
    ]
